# Generated by Django 2.2.4 on 2019-08-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pet_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='admin',
        ),
    ]
